### ISSUE TITLE
Packages Upgrade

### ISSUE THREAD

**Issue by soufiane-bouchaara** [capsule-corp-ternoa/ternoa-workshop#5]
<img width="535" alt="image" src="https://user-images.githubusercontent.com/2540416/185203063-ebd7100d-8ef4-43ee-a107-94b60c5dfcd0.png">

**Comment by ipapandinas** [comment]
Solved in this PR: https://github.com/capsule-corp-ternoa/ternoa-workshop/commit/e7481039c2490cc003a53108c5a4ad9baf52056c
